### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by mikey427** [swiftplague/Altis_life#1]
Misspellings:
License - Pyrgos - 169126
Processing: Cocaine Processing - Pyrgos - 167127
Supermarket - Molos - 169233
Police Station - AAC Airfield - 115119
ADAC Market - Kavala - 032129
Market - Sofia - 256213
Gold Mine - 232223

Bugs:
Remove the "Note: Things that are illegal do not save when you park it (vehicle) in garage."

**Comment by nightthriver** [comment]
Southern Border Crossing
It's almost entirely f**ked up as far as vehicles spawning and garages.

**Comment by swiftplague** [comment]
Finished updating map these should be fixed in next iteration will close if they work then
